#!/usr/bin/env python3
import sys
from nmigen.back             import rtlil
from nmigen._toolchain.yosys import *
from nmigen.hdl.ir           import Fragment
import click
import importlib
import inspect
from inspect import Signature, Parameter

def _show_rtlil_text(rtlil_text, *, src_loc_at=0):
    yosys = find_yosys(lambda ver: ver >= (0, 9, 3468))
    yosys_version = yosys.version()

    module_prefix = "module \\"

    modules = [
        m.replace(module_prefix, "") for m in rtlil_text.split('\n')
                                     if m.startswith(module_prefix)]

    script = []
    script.append("read_ilang <<rtlil\n{}\nrtlil".format(rtlil_text))

    if yosys_version >= (0, 9, 3468):
        # Yosys >=0.9+3468 (since commit 128522f1) emits the workaround for the `always @*`
        # initial scheduling issue on its own.
        script.append("delete w:$verilog_initial_trigger")

    for module in modules:
        script.append("show -nobg -colors 42 " + module)

    return yosys.run(["-q", "-"], "\n".join(script), src_loc_at=1 + src_loc_at)

def do_show(*args, **kwargs):
    rtlil_text = rtlil.convert(*args, **kwargs)
    return _show_rtlil_text(rtlil_text, src_loc_at=1)

@click.group()
def cli():
    pass

@cli.command()
@click.argument('class_name')
def show(class_name: str):
    sys.path.append('.')
    parts = class_name.split('.')
    package_name = ".".join(parts[:-1])
    top_name = parts[-1]
    module = importlib.import_module(package_name)
    design_class = module.__dict__[top_name]
    if not inspect.isclass(design_class):
        print(top_name + " is not a class! exiting...")
        sys.exit(1)

    args = []
    kwargs = {}
    signature = inspect.signature(design_class.__init__)
    for parameter in signature.parameters.values():
        if parameter.name == "self":
            continue

        if (parameter.default == Signature.empty):
            val = input(f"parameter {parameter.name} value: ")

            val_type = int
            if parameter.annotation != Parameter.empty:
                val_type = parameter.annotation
            else:
                val_type_str = input(f"parameter {parameter.name} type: ")
                val_type = eval(val_type_str)

            value = val_type(val)
            if parameter.kind == Parameter.KEYWORD_ONLY:
                kwargs[parameter.name] = value
            elif parameter.kind == Parameter.POSITIONAL_ONLY:
                args.append(value)

    design = design_class(*args, **kwargs)
    fragment = Fragment.get(design, None)
    do_show(fragment)

if __name__ == '__main__':
    cli()
